name: percepta

networks:
  percepta:
    external: true

services:
  percepta:
    image: percepta:latest

    container_name: percepta

    ports:
      - "8001:8001"

    volumes:
      - ./src:/app/src
    
    networks:
      - percepta
