name: percepta-ingester

networks:
  percepta:
    external: true

services:
  percepta:
    image: percepta-ingester:latest

    container_name: percepta-ingester

    ports:
      - "8001:8000"

    volumes:
      - ./src:/app/src
      - .env:/app/.env
    
    networks:
      - percepta
